
import os
import sys
import logging
from pprint import pprint

# Setup path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.config import Config
from backend.utils.llm_client import LLMFactory
from backend.engine.questions import QuestionGenerator

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def verify_ollama():
    print(f"Checking Ollama Configuration...")
    print(f"Base URL: {Config.OLLAMA_BASE_URL}")
    print(f"Model: {Config.OLLAMA_MODEL}")
    
    # 1. Test Factory
    print("\n1. Testing LLM Factory...")
    client = LLMFactory.create_client()
    if client:
        print(f"✅ Client created: {client.__class__.__name__}")
    else:
        print("❌ Failed to create LLM client")
        return

    # 2. Test Question Generation
    print("\n2. Testing Question Generation (this may take a few seconds)...")
    generator = QuestionGenerator()
    
    content = """
    Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation.
    Python is dynamically-typed and garbage-collected. It supports multiple programming paradigms, including structured (particularly procedural), object-oriented and functional programming.
    """
    
    try:
        questions = generator.generate_questions(
            content=content,
            num_questions=1,
            difficulty="easy",
            topic="Python Basics",
            use_rag=False
        )
        
        if questions:
            print(f"✅ Successfully generated {len(questions)} question(s)")
            pprint(questions[0])
            
            # Check if it was fallback
            if 'fallback' in questions[0].get('id', ''):
                 print("⚠️ WARNING: Questions were generated using FALLBACK logic (not AI). check Ollama connection.")
            else:
                 print("🎉 Success: Question generated by AI model.")
        else:
            print("❌ No questions returned.")
            
    except Exception as e:
        print(f"❌ Error during generation: {e}")

if __name__ == "__main__":
    verify_ollama()
